### ISSUE TITLE
Missing GT-files

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/gt-repo-template#2]
# Description

Current action workflow fails, and I can't figure out why, see [gt-test](https://github.com/M3ssman/gt-test).

I used the same structure like the one we tried together, only with more items (16) and some meaningful MODS-metadata for each image, respectively.

Whereas the images with their absolute URLs are present, job [make bagit](https://github.com/M3ssman/gt-test/actions/runs/6234261061/job/16921115898) seems to miss the gt files, which are relative to the project:

```
 10:50:55.547 INFO ocrd.workspace_bagger - Handling OcrdFile <OcrdFile fileGrp=OCR-D-IMG ID=IMG_MAX_1290695, mimetype=image/jpeg, url=https://opendata.uni-halle.de/retrieve/aca4b878-c92b-47b7-92e7-99da69c00846/00000442.jpg, local_filename=---]/> 
10:50:56.949 INFO ocrd.workspace_bagger - Handling OcrdFile <OcrdFile fileGrp=FULLTEXT ID=FULLTEXT_1, mimetype=application/alto+xml, url=---, local_filename=---]/> 
Traceback (most recent call last):
  File "/home/runner/.local/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/ocrd/cli/zip.py", line 54, in bag
    workspace_bagger.bag(
  File "/home/runner/.local/lib/python3.10/site-packages/ocrd/workspace_bagger.py", line 175, in bag
    total_bytes, total_files = self._bag_mets_files(workspace, bagdir, ocrd_mets, processes)
  File "/home/runner/.local/lib/python3.10/site-packages/ocrd/workspace_bagger.py", line 80, in _bag_mets_files
    self.resolver.download_to_directory(file_grp_dir, f.url, basename=f.basename)
  File "/home/runner/.local/lib/python3.10/site-packages/ocrd/resolver.py", line 63, in download_to_directory
    raise ValueError(f"'url' must be a non-empty string, not '{url}'") # actually Path also ok
ValueError: 'url' must be a non-empty string, not ''
```

??

**Comment by Boenig** [comment]
Hallo Uwe,

The problem lies in the METS file. 
The linking/referencing of the PAGE file is only specified by the `LOCTYPE` attribute with the value `OTHER`. In this case, the attribute `OTHERLOCTYPE` with the value `FILE` must also be specified.

The following changes or extensions must be made:

```xml
<mets:FLocat xlink:href="GT-PAGE/[optional folder]/[PAGE-File.xml]" LOCTYPE="OTHER" OTHERLOCTYPE="FILE"/>
```

Regards
Matthias
